<?php
global $site;
$site->get_template('footer'); ?>

<link rel="stylesheet" href="/resources/js/vendor/highlight/styles/default.css">

<script src="/resources/js/vendor/jquery-3.1.1.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/resources/js/vendor/highlight/highlight.pack.js" type="text/javascript" charset="utf-8"></script>

<script src="/resources/js/nice-fiddle.js" type="text/javascript" charset="utf-8"></script>
<script src="/pages/classcarousel/resources/js/min/classcarousel-min.js" type="text/javascript" charset="utf-8"></script>

<script>hljs.initHighlightingOnLoad();</script>
<script type="text/javascript">
	// init demo
	jQuery('#cc_demo').classCarousel({visible: 5});

	// TOC scroll anchor animation
	jQuery(document).on('click', '.toc a', function(e){
		var rulerHeight = 20,
			offset = 20,
			$el = $($(this).attr('href'));

		if($el.length)
		{
			e.preventDefault();
			$('html, body').animate({ scrollTop: $el.offset().top - (rulerHeight + offset) }, 600);
		}
	});

	jQuery('#contact-form').niceForm();
</script>

<!-- <script src="/resources/js/combined.js?v=1.0" type="text/javascript" charset="utf-8" defer></script> -->
