<?php global $site; ?>
<div id="wrapper">
	<section id="content">
		<header>
			<h1>ClassCarousel</h1>
			<span class="subline">
				A lightweight(2.23kb minified) css based carousel bootstrap
			</span>

			<a title="ClassCarousel JS" href="https://github.com/krinkled/ClassCarousel" class="btn" target="_blank" data-track="Classcarousel github link" data-track-type="external-link">Download on GitHub</a>
		</header>

		<div id="cc_demo">
			<div class="actions">
				<button type="button" cc-control="prev">Previous</button>
				<button type="button" cc-control="next">Next</button>
				<button type="button" cc-control="prev-set">Previous set</button>
				<button type="button" cc-control="next-set">Next set</button>
			</div>
			<ul class="items">
				<?php
				for($i=0; $i<=40; $i++)
				{
					printf('<li class="item">Item %s</li>', $i + 1);
				}
				?>
			</ul>
		</div>
	</section>

	<section id="plugin-information">
		<div class="side">
			<ul class='toc'>
				<li><a href="#introduction" title="">Introduction</a></li>
				<li><a href="#download" title="">Download</a></li>
				<li><a href="#how-it-works" title="">How it works</a></li>
				<li><a href="#getting-started" title="">Getting started</a></li>
				<li><a href="#examples" title="">Examples</a></li>
				<li><a href="#faq" title="">FAQ</a></li>
			</ul>
		</div>
		<div class="content-container">
			<div id="introduction">
				<p style="font-size: 1.8rem; margin-top: 0;">With this plugin you can create slide-shows, content tickers and any other kind of carousel for websites, based on css animations. The jQuery plugin will add classes to each of the selected items. Each of these classes has info about it's current position in the carousel. You can create positions for those locations, and next css transition will do the work for you. It's lightweight and simply written to be readable, tiny (2.23kb minified) and understandable. With the events and controls you should be able to extend it for your needs. Enjoy and let me know if there are questions / suggestions.</p>
				<h2 id="how-it-works">How it works</h2>
				<p>You can put any kind of content inside it's items. Do mind that the items are actually rendered all the time, so for instance, dont play movies constantly. Instead use the jQuery events to load heavy content on activation of the slide, in the meantime you could show a preview image while it's not active.</p>
				<p>When the plugin is activated, it will put classes onto each element it matches, based on there position. When you use the controls to change to next or previous item/set, the classes of the elements will change according to your choice of action. The elements wont move by javascript, but their locations need to be defined in css. (The css transition property will then do all the action for you)</p>
				<p>In CSS you can define positions for each of the active locations, as well as the hidden-left/-right location. When after that, css transition is applied, the items will slide intro there new locations according to your control ;-)</p>
				<?php jsfiddle('Class shifting example', 'Louj3hjo', 8, 320); ?>
				<p>I've made some basic examples in the examples section. Be sure to check that before you start! You can probably use one of them as your bootstrap.</p>
			</div>
			<div id="download">
				<h2>Download</h2>
				<p>You can download the latest version <a title="ClassCarousel JS" href="/files/jquery.classcarousel.js">here</a></p>
			</div>
			<div id="getting-started">
				<h2>Getting started</h2>
				<p>Use the plugin as follows:</p>
				<pre><code lang="javascript">$('.class-carousel').classCarousel();</code></pre>
				<div class="row">
				<div class='col'>
				<h2>Plugin options</h2>
				<dl>
					<dt>visible</dt>
					<dd>number of 'visible' items in the carousel; eg. loc_1, loc_2,</dd>
					<dt>offset</dt>
					<dd>provides a starting offset</dd>
					<dt>cycle_set_timout</dt>
					<dd>Timeout between iterations when user cycles a set.</dd>
					<dt>cycle</dt>
					<dd>cycle carousel? false = stop at end of items</dd>
					<dt>child_selector</dt>
					<dd>what children should be selected as items?</dd>
				</dl>
				</div>

				<div class='col'>
					<h2>Default configuration</h2>
				<pre><code lang="javascript">var settings = {
	visible: 4,
	offset: 0,
	cycle_set_timout: 50,
	cycle: true,
	child_selector: '.items > *'
};</code></pre>
			</div></div></div>

			<div id="examples">
				<h2>Examples</h2>
				<p></p>
				<?php jsfiddle('Horizontal example', '9sacgfxs', 8, 250); ?>
				<?php jsfiddle('Vertical example','1zjpxk72', 9, 550); ?>
				<?php jsfiddle('Funky example','ar09d9pm', 5, 550); ?>
				<?php jsfiddle('Simple ticker example','228t8v8f', 5, 350); ?>
			</div>

			<div id="faq">
				<h2>Frequently asked questions</h2>
				<p>None yet actualy, but i would love to hear your questions or feedback.</p>
				<a href="/#!/contact">Leave your questions and/or feedback here.</a>
			</div>
		</div>
	</section>
</div>
