<?php
global $site;
$site->get_template('footer'); ?>

<link rel="stylesheet" href="/resources/js/vendor/highlight/styles/default.css">
<script src="/resources/js/vendor/highlight/highlight.pack.js" type="text/javascript" charset="utf-8"></script>
<script>hljs.initHighlightingOnLoad();</script>



<script type="module" src="/pages/es6-moremenu/resources/js/demo.js"></script>
<script  src="/pages/es6-moremenu/resources/js/es5-notice.js" nomodule></script>