<?php global $site; ?>
<form action="/" method="post" accept-charset="utf-8" id="contact-form" class="content">
	<input type="hidden" name="location" value="<?php echo $site->page; ?>">
	<div class="field">
		<input placeholder="Name" type="text" name="name">
	</div>
	<div class="field">
		<input placeholder="Email" type="email" name="email">
	</div>
	<div class="field">
		<textarea placeholder="Message" name="message"></textarea>
	</div>
	<div class="field company">
		<input type="text" name="company" value="">
	</div>
	<button type="submit">Send</button>
</form>
