<!DOCTYPE html>
<html>
<head>
	<style type="text/css" media="screen">
		html, body{ height: 100%; margin: 0px; background-color: #f2f2f2;}
		#table td, #table th{ padding: 5px; }
	</style>
</head>
<body>
	<div class="wrap" style="background-color: #f2f2f2; padding: 100px 0 200px;">
		<div class="content" style="font-size:16px; font-family: Arial; max-width: 400px; padding:20px; margin: 0 auto; background: #fff; box-shadow: 0 1px 3px 0 rgba(0,0,0,.2), 0 1px 1px 0 rgba(0,0,0,.14), 0 2px 1px -1px rgba(0,0,0,.12);">
			<h2 style="margin-left:4px; margin-top: 0px;color: #333;">Website contact verzoek</h2>
			<table id="table">
				<tbody>
					<tr>
						<th style="text-align: left;color: #333;">Naam:</th>
						<td style="color: #333;">{{name}}</td>
					</tr>
					<tr>
						<th style="text-align: left;color: #333;">Email:</th>
						<td style="color: #333;">{{email}}</td>
					</tr>
					<tr>
						<th style="text-align: left;color: #333;">Bericht:</th>
						<td style="color: #333;">{{message}}</td>
					</tr>
					<tr>
						<th style="text-align: left;color: #333;">Ingevuld op:</th>
						<td style="color: #333;">{{location}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>
