<?php global $site; ?>
<div id="wrapper">

	<section id="content">
		<header>
			<h1>MoreMenu</h1>
			<span class="subline">
				A lightweight(2.1kb minified) moremenu jQuery plugin
			</span>

			<a title="MoreMenu JS" href="https://github.com/jvineveld/MoreMenu" class="btn" target="_blank" data-track="MoreMenu github link" data-track-type="external-link">Download on GitHub</a>
		</header>

		<div id="mm_demo">
			<div class="demo-body">
				<ul class="menu">
					<li><a href="#">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li class="has-subs">
						<a href="#">Top line</a>
						<ul>
							<li><a href="#">Red products</a></li>
							<li><a href="#">Blue products</a></li>
						</ul>
					</li>
					<li class="has-subs">
						<a href="#">Bottom line</a>
						<ul>
							<li><a href="#">Red products</a></li>
							<li><a href="#">Blue products</a></li>
						</ul>
					</li>
					<li class="has-subs">
						<a href="#">Sweet line</a>
						<ul>
							<li><a href="#">Red products</a></li>
							<li><a href="#">Blue products</a></li>
						</ul>
					</li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Service</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
			<span id="demo-sizing-bar"></span>
		</div>
	</section>

	<section id="plugin-information">
		<div class="side">
			<ul class='toc'>
				<li><a href="#introduction" title="">Introduction</a></li>
				<li><a href="#how-it-works" title="">How it works</a></li>
				<li><a href="#getting-started" title="">Getting started</a></li>
				<li><a href="#examples" title="">Examples</a></li>
				<li><a href="#faq" title="">FAQ</a></li>
			</ul>
		</div>
		<div class="content-container">
			<div id="introduction">
				<p style="font-size: 1.8rem; margin-top: 0;">With this plugin you can add more menu functionality to your website.</p>
				<h2 id="how-it-works">How it works</h2>
				<p>When the menu is initialized on a menu, it will check how many items fit on it's row. The not fitting items will be placed inside a 'more..' menu item. This way you wont have trouble making menu items fit on a small device.</p>
			</div>
			<div id="getting-started">
				<h2>Getting started</h2>
				<p>Use the plugin as follows:</p>
				<pre><code lang="javascript">$('#menu').moreMenu();</code></pre>
				<div class="row">
				<div class='col'>
				<h2>Plugin options</h2>
				<dl>
					<dt>verb.more_link</dt>
					<dd>Label of the 'more' menu item.</dd>
					<dt>more_menu_location</dt>
					<dd>Where should the more menu be placed? Possible to pass a selector or element</dd>
					<dt>class_target</dt>
					<dd>on what element should the classes change when user toggles and moremenu is initialized? Possible to pass a selector or element.</dd>
					<dt>menu_item</dt>
					<dd>What type of menu items are we looking for?</dd>
					<dt>extra_offset</dt>
					<dd>providing extra offset makes the menu items move into the moremenu sooner.</dd>
				</dl>
				</div>

				<div class='col'>
					<h2>Default configuration</h2>
				<pre><code lang="javascript">var settings = {
	verb: {
		more_link: '<span>More..</span>'
	},
	more_menu_location: 'after_menu',
	class_target: 'more_menu',
	menu_item: '> li',
	extra_offset: 0
};</code></pre>
			</div></div></div>

			<div id="faq">
				<h2>Frequently asked questions</h2>
				<p>None yet actualy, but i would love to hear your questions or feedback.</p>
				<a href="/#!/contact">Leave your questions and/or feedback here.</a>
			</div>
		</div>
	</section>
</div>
